### ISSUE TITLE
Support for Lovense Gravity

### ISSUE THREAD

**Issue by Krimmblz** [SutekhVRC/VibeCheck#12]
Hello
I was just wondering if you're planning on adding support for the newly released Lovense Gravity toy!
Or will it already work?
There is sadly no way to test it out yet, considering that it hasn't arrived for anyone.
Kind regards

**Comment by SutekhVRC** [comment]
Yes, there will be added support for the Lovense Gravity, Flexer, and Gemini!

**Comment by Krimmblz** [comment]
Thanks for the quick response!
Is there an ETA on that?

**Comment by SutekhVRC** [comment]
Not far away, you can track our development in the new discord in #github-updates if you would like!

As for the support for newer toys, they will probably be added by the time its released!
